version: '3.9'
services:
  hextasks-dev:
    build:
      context: ../..
      dockerfile: ./docker/postgres/Dockerfile
      target: dev
    ports:
      - '3000:3000'
    links:
      - postgres
    depends_on:
      - postgres
    volumes:
      - ../..:/home/app
    environment:
      - DIALECT=POSTGRES
      - DB_URL=postgres://postgres:admin@postgres:5432/hextasks
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=hextasks
