version: '3.9'
services:
  hextasks:
    build:
      context: ..
      dockerfile: ./apps/express/Dockerfile
      target: dev
    ports:
      - '3000:3000'
    environment:
      - JWT_SECRET=secret
    volumes:
      - ..:/app
