FROM node:20-alpine as base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

FROM base as deps
WORKDIR /app
RUN mkdir -p /app
COPY package.json  ./
RUN pnpm install 

FROM base as dev
WORKDIR /app
COPY --from=deps /app/node_modules /app/node_modules
COPY src package.json ./app

EXPOSE 3000

CMD ["pnpm", "dev:express"] 

# TODO: the test stage is not working
# because the dependencie bcrypt is not working
FROM base as test
WORKDIR /app
ENV NODE_ENV test
COPY --from=deps /app/node_modules /app/node_modules
COPY . .

CMD ["pnpm", "test"]