version: '3.9'
services:
  hextasks-mongo:
    build:
      context: ../..
      dockerfile: ./apps/express/Dockerfile
      target: dev
    ports:
      - '3000:3000'
    links:
      - mongo
    volumes:
      - ../..:/app
    environment:
      - JWT_SECRET=secret
      - DIALECT=MONGODB
      - DB_URL=mongodb://admin:secret@mongo:27017/hextasks?authSource=admin
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
